// pages/layout.js
import dynamic from "next/dynamic";
import React from "react";
import { Inter } from "next/font/google";
const Navbar = dynamic(()=>import("../Components/Navbar"))
const Footer = dynamic(()=>import("../Components/Footer"))

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const Layout = ({ children }) => (
  <>
    <Navbar />
    <div className={inter.className}>
      {children}
    </div>
    <Footer />
  </>

);

export default Layout;

